name: CI-CD Pipeline

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # --------------------
      # 1. Security Scan Before Build
      # --------------------
      - name: Trivy FS Scan (source code scan)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          severity: HIGH,CRITICAL
          exit-code: 0
          path: .

      # --------------------
      # 2. Build Docker image
      # --------------------
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_IMAGE }}:${{ github.sha }} .

      # --------------------
      # 3. Security Scan After Build
      # --------------------
      - name: Trivy Image Scan (Docker image scan)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          ignore-unfixed: true
          format: table
          severity: HIGH,CRITICAL
          exit-code: 0
          image-ref: ${{ secrets.DOCKER_IMAGE }}:${{ github.sha }}

      # --------------------
      # 4. SonarQube Scan
      # --------------------
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://<EC2_PUBLIC_IP>:9000   # if using your EC2 SonarQube
          # or https://sonarcloud.io if using SonarCloud

      # --------------------
      # 5. Push Docker image
      # --------------------
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_IMAGE }}:${{ github.sha }}
          docker tag ${{ secrets.DOCKER_IMAGE }}:${{ github.sha }} ${{ secrets.DOCKER_IMAGE }}:latest
          docker push ${{ secrets.DOCKER_IMAGE }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Create deploy directory if not exists
            mkdir -p ~/deploy
            cd ~/deploy

            # Save deploy.sh (from repo)
            cat <<'EOF' > deploy.sh
            #!/bin/bash
            set -e
            APP_NAME="swiggy-app"
            IMAGE="${DOCKER_IMAGE:-${{ secrets.DOCKER_IMAGE }}:latest}"

            echo "🔄 Pulling latest Docker image..."
            docker pull $IMAGE

            echo "🛑 Stopping old container..."
            docker stop $APP_NAME || true
            docker rm $APP_NAME || true

            echo "🚀 Starting new container..."
            docker run -d -p 80:3000 --name $APP_NAME $IMAGE

            echo "✅ Deployment complete!"
            EOF

            chmod +x deploy.sh
            ./deploy.sh
